### ISSUE TITLE
Create wrapper and clean task in root build.gradle file

### ISSUE THREAD

**Issue by Gwindor** [Solod/BadParking#4]

**Comment by Solod** [comment]
please see, correctly implemented?

**Comment by Gwindor** [comment]
create pull request for that

**Comment by Gwindor** [comment]
And I do not se any changes about that. I saw changes around gradle plugin but this is another issue

**Comment by Gwindor** [comment]
task clean(type: Delete) {
    delete rootProject.buildDir
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.10'
}

**Comment by Solod** [comment]
Is that what you wanted?

**Comment by Gwindor** [comment]
If you create pull request assigned to me I will close issue by myself and you should not ask me avery time.
